import sys
from src.utils.logger import logging
from src.utils.exception import CustomException
from src.agents.base_agent import BaseAgent
from src.models.state import DevTeamState

class DeveloperAgent(BaseAgent):
    """
    DeveloperAgent is responsible for generating backend code
    based on the system architecture provided by the ArchitectAgent.

    The agent acts as a Python Backend Developer and generates
    production-ready FastAPI code following best practices.
    """

    def __init__(self):
        """
        Initialize the DeveloperAgent with a system prompt that
        instructs the LLM to generate FastAPI backend code.
        """

        logging.info("Initializing DeveloperAgent")

        system_prompt = """
        You are a Python Backend Developer.
        Write production-ready FastAPI code.
        """

        # Initialize the BaseAgent with the system prompt
        super().__init__(system_prompt)

        logging.info("DeveloperAgent initialized successfully")

    def execute(self, state: DevTeamState):
        """
        Executes the code generation process.

        Parameters
        ----------
        state : DevTeamState
            Shared workflow state containing outputs from previous agents.
            Expected key:
                - architecture : System architecture generated by ArchitectAgent

        Returns
        -------
        dict
            Dictionary containing generated backend code.
        """

        try:
            logging.info("DeveloperAgent execution started")

            # Generate backend code using the LLM
            code = self.run(state["architecture"])

            logging.info("Code generation completed successfully")

            # Return result in workflow state format
            return {"code": code}

        except Exception as e:
            logging.error("Error occurred during code generation in DeveloperAgent")
            raise CustomException(e, sys)