import sys
from src.utils.logger import logging
from src.utils.exception import CustomException
from src.agents.base_agent import BaseAgent
from src.models.state import DevTeamState

class QAAgent(BaseAgent):
    """
    QAAgent is responsible for generating automated unit tests
    for the code produced by the DeveloperAgent.

    The agent acts as a QA Engineer and generates:
        - Pytest unit tests
        - Test cases for API endpoints
        - Edge case validations
        - Basic functional verification
    """

    def __init__(self):
        """
        Initialize the QAAgent with a system prompt that instructs
        the LLM to generate pytest-based unit tests.
        """

        logging.info("Initializing QAAgent")

        system_prompt = """
        You are a QA Engineer.
        Write pytest unit tests for the code.
        """

        # Initialize the BaseAgent with the QA system prompt
        super().__init__(system_prompt)

        logging.info("QAAgent initialized successfully")

    def execute(self, state: DevTeamState):
        """
        Executes the test generation process.

        Parameters
        ----------
        state : DevTeamState
            Shared workflow state containing outputs from previous agents.
            Expected key:
                - code : Source code generated by DeveloperAgent

        Returns
        -------
        dict
            Dictionary containing generated pytest test cases.
        """

        try:
            logging.info("QAAgent execution started")

            # Generate tests using the LLM
            tests = self.run(state["code"])

            logging.info("Test generation completed successfully")

            # Return tests in expected workflow state format
            return {"tests": tests}

        except Exception as e:
            logging.error("Error occurred during test generation in QAAgent")
            raise CustomException(e, sys)