from typing import TypedDict
from src.utils.logger import logging

logging.info("Initializing DevTeamState schema for DevTeam workflow")

class DevTeamState(TypedDict):
    """
    TypedDict representing the shared workflow state.

    Each key represents data produced or consumed by agents
    in the AI development pipeline.
    """

    # Initial user input describing the software requirement
    user_request: str

    # Product specification generated by ProductManagerAgent
    product_spec: str

    # System architecture designed by ArchitectAgent
    architecture: str

    # Backend code generated by DeveloperAgent
    code: str

    # Unit tests generated by QAAgent
    tests: str

    # Code review feedback generated by CodeReviewAgent
    review: str